sse_starlette/sse.py
Pings are muddling `message` events when it is [intended](https://github.com/sysid/sse-starlette/blob/master/sse_starlette/sse.py#L204-L206) that `pings` are sent as "comments" 
*Network tab in dev-tools* 
The ping string `: ping [TIMESTAMP]` is sent through the `data` field when it should be on a line on its own (as seen in the [MDN example](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Data-only_messages)) for it to be recognized as a comment.
Given a simple SSE endpoint that streams numbers:
```python
@app.get("/sse")
async def sse(req: Request):
async def streamNumbers(num):
i = 0
while i <= num:
disconnected = await req.is_disconnected()
if disconnected:
break
yield i
i += 1
await asyncio.sleep(1)
return …
```
=> Send pings as a custom `ping` event

sse_starlette/sse.py
Thanks for the quick response at #3 @sysid. I just realized that I didn't update the comment in the `_ping()` method. Sorry about that.
=> fix: Update comment in _ping() method

setup.py
I added starlette/py.typed file and update setup.py to include "package_data" line.
I tried to use sse-starlette with mypy, but it claims `Skipping analyzing 'sse_starlette.sse': found module but no type hints or library stubs`.
I found that's probably because of lack of py.typed file (PEP 561).
=> feat: add py.typed for enable type checking

README.md, example.py
Hopefully this will help clarity for future users of sse-starlette. This is an update to the documentation to show handling of connection closes due to refresh/tab-closing. Starlette doesn't disconnect the request, it cancels the future/task. Therefore checking for `req.is_disconnected()` won't ever get called and it will just die. Wrapping it all in a try/except CancelledError will keep the loop from dying (giving you time to cleanup, log, or anything else)
=> Explicit handling of refresh/tab-close in the examples

example_fastapi.py, sse_starlette/sse.py
Hi, thanks for the nice library :wave:
I have a FastAPI endpoint that is similar to your example, but only yields when there is new data. As a consequence your AppStatus check does not force my endpoint to close, because there is no yielded item to get into the codepath that checks AppStatus.
I updated your fastapi example to reflect this use-case and added a third task to `run_until_first_complete` that checks the uvicorn exit status at a regular interval.
=> update fastapi example to use conditional yielding endpoint 

sse_starlette/sse.py
Current implementation ignores the charset field in the response class, which may lead to some problem, while [starlette handles that properly](https://github.com/encode/starlette/blob/master/starlette/responses.py#L59-L80)
So we can reuse starlette's code to set proper content-type and charset, like changing [this line](https://github.com/sysid/sse-starlette/blob/master/sse_starlette/sse.py#L170).
=> fix charset

README.md, sse_starlette/sse.py
To support fan out proxies like fastly the response needs to
be cacheable.
ref: https://github.com/sysid/sse-starlette/issues/34
closes https://github.com/sysid/sse-starlette/issues/34
=> feat(sse/cache-control): allow user to set cache-control header

examples/custom_generator.py, sse_starlette/sse.py, tests/integration_testing.http
=> feat: add support for custom async iterable objects

sse_starlette/sse.py, tests/test_sse.py
Given 3 users who have made a comment on the ping events in #51 and #44 -- it might be best to send pings as comments by default, that way clients don't have to deal with them out-of-the box.
To achieve this, we can change the ping from an event data to an event comment as seen on this changeset, 
However, the package does not seem to be encoding the events properly when a comment is included in the event. Examples,
1. If the event only includes a comment, `ServerSentEvent(comment="a comment")`, then
- expected encoded event is `: a comment\r\n\r\n`
- but actual encoded event is: `: a comment\r\n`
2. If the event includes data and a comment, `ServerSentEvent(data="some data", comment="a comment")`
- expected encoded event is `: a comment\r\ndata: some data\r\n\r\n`
- but actual encoded …
=> feat: Send pings as comments by default

README.md, examples/no_async_generators.py, sse_starlette/sse.py, tests/test_event_source_response.py
This PR adds a new option that runs the code that generates responses in the same TaskGroup that is used for streaming the response. Doing so avoids the need for an async generator or some other form of persistent iterator that exists across requests.
The motivation for doing that is that async generators have less well defined error and cleanup behavior especially when they are interrupted [see here](https://vorpus.org/blog/some-thoughts-on-asynchronous-api-design-in-a-post-asyncawait-world/#cleanup-in-generators-and-async-generators).
In this new implementation, the coroutine that is generating outputs can be straightforwardly cancelled just like all the others in response to disconnects or server shutdowns and will be able to run its cleanup code right then and there which makes it …
=> Allow Usage without Async Generators

sse_starlette/sse.py
So `AppStatus.should_exit_event` got rewrited in `listen_for_exit_signal` with every new connection being made and old connections remain in connected state when server stops.
This fixes that.
=> fix: there should be only one exit event

sse_starlette/sse.py
- the spec defines "id" as an opaque UTF-8 string with no NUL/CR/LF bytes
- the type in the doc string was already correct
https://html.spec.whatwg.org/multipage/server-sent-events.html#the-last-event-id-header
=> fix type of SSE "id" field (int->str)

sse_starlette/sse.py
the `retry` field is for instructing the client to wait before trying to reconnect in case of connection loss
https://html.spec.whatwg.org/multipage/server-sent-events.html#concept-event-stream-reconnection-time
=> fix docstring for the "retry" kwarg

pdm.lock, sse_starlette/sse.py, tests/anyio_compat.py, tests/integration/frozen_client.py, tests/test_event_source_response.py, tox.ini
As described in #89, this adds a `send_timeout` parameter to the `EventSourceResponse` initializer. In the event of the `send` call inside the response's sending logic exceeding this duration, a `SendTimeoutError` is raised, aborting the SSE event generator and effectively canceling the HTTP connection.
=> [#89] Add SSE Send Timeout

sse_starlette/sse.py
Using `EventSourceResponse(sep="\n"`, I expect the default ping SSE to use this separator, but it's currently not forwarded.
=> fix: honor custom separator in ping sse

.gitignore, .pdm-python, README.md, tests/integration/test_multiple_consumers.py
As we talked about in the commit comments, here is my PR removing the unused event loop.
During development I found some small typos in the README.md which I took the liberty to fix.
Creating and activating my development environment the content of .pdm-python changed, I removed the file from the repo and added it to git ignore since it contains a machine specific path to a virtual environment.
=> Cleanup unused loops

sse_starlette/sse.py
The old page now 404s, so I've changed the link to use the new spec
=> Update link to new spec

Makefile, pyproject.toml, sse_starlette/sse.py, tests/test_event_source_response.py
The default cache-control header returned by sse-starlete is
"no-cache", which (confusingly!) does not actually mean "don't cache",
but instead that caching is allowed but the result must be
re-validated on each fetch.  [From MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control):
> The no-cache response directive indicates that the response can be
> stored in caches, but the response must be validated with the origin
> server before each reuse, even when the cache is disconnected from
> the origin server.
This is *probably* harmless as long as there's not an ETag or
Last-Modified header that would allow revalidation, but it does make
it much easier to unexpectedly enable caching or globally audit cache
behavior.
This PR:
* Changes the default to "no-store", which …
=> Change default cache-control response to 'no-store'

examples/stream_generator.py, examples/stream_generator_multiple.py
Problem:
`asyncio.Queue()` should be called inside `asyncio.run()`, because it used `asyncio.get_event_loop()` / `asyncio.get_running_loop()`.
Solution:
delay initialized `Stream._queue`.
=> Fix streaming examples cannot be running in python3.9

tox.ini
`testcontainers` and `async-timeout` are listed in GHA workflow, but are missed in `tox.ini`.
I think that's a good idea to add them to `tox.ini` for people, who run tests locally.
=> add missing test dependencies to tox.ini

README.md, sse_starlette/__init__.py, sse_starlette/event.py, tests/test_event.py
Using this library manually managing `json.dumps` was quite a chore, so naturally some wrappers were made.
As a continuation of https://github.com/sysid/sse-starlette/issues/21 and https://github.com/sysid/sse-starlette/pull/79, a neat way to improve the QOL of this library would be to provide a neat wrapper that immitates the common `JSONResponse` seen in starlette (https://github.com/encode/starlette/blob/fa5355442753f794965ae1af0f87f9fec1b9a3de/starlette/responses.py#L180).
I've added a simple test case and an entry to the README.md, but let me know if any changes are required. The actual behavior of the class is losely related to `JSONResponse` but `None` is treated as `None` all the way through, not null.
=> Add an `JSONServerSentEvent` utility based on starlette `JSONResponse`
